# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a32fca1370cbccca61dd7fc55dfae327a108a120b036d3b3423dc917651a09b2fb705194f9a3dabd53e18de439b6703da2fe89e0cbea9d9762ecc32d00eb3bd

test:
  secret_key_base: eae588f72b4f2fb85e665a5164d1c94af7f753f4dfb73ce71aee7abd74357b75709e090670ddf76df9522bf98778c7c211afa6c4e2c6449026e6eabc4d343356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
